[tool.coverage.run]
  omit = [
    "*/stream_ml/conftest.py",
    "*setup_package*",
    "*/stream_ml/tests/*",
  ]

[tool.coverage.report]
  exclude_lines = [
    # Have to re-enable the standard pragma
    # and branches that don't pertain to this version of Python
    "pragma: no cover",
    "pragma: py{ignore_python_version}",
    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",
    # Don't complain if non-runnable code isn't run
    "if __name__ == .__main__.:",
    # Don't complain about abstract methods, they aren't run:
    '@(abc\.)?abstractmethod',
    # Exclude type check blocks and Protocol contents, they aren't run:
    "if TYPE_CHECKING:",
    '\.\.\.',
    # Don't complain about IPython completion helper
    "def _ipython_key_completions_",
  ]


[tool.isort]
  profile = "black"
  include_trailing_comma = "True"
  use_parentheses = "True"
  ensure_newline_before_comments = "True"
  known_localfolder = ["stream_ml", "stream_ml.jax"]
  known_third_party = ["numpy", "pytest"]
  import_heading_stdlib = "STDLIB"
  import_heading_firstparty = "FIRST-PARTY"
  import_heading_thirdparty = "THIRD-PARTY"
  import_heading_localfolder = "LOCAL"


[tool.mypy]
  namespace_packages = true
  explicit_package_bases = true
  mypy_path = "$MYPY_CONFIG_FILE_DIR/libs/core/src:$MYPY_CONFIG_FILE_DIR/libs/pytorch/src:$MYPY_CONFIG_FILE_DIR/libs/jax/src"

  strict = true
  disallow_subclassing_any = false
  disallow_untyped_defs = true
  ignore_missing_imports = true
  no_implicit_optional = true
  warn_return_any = true
  warn_redundant_casts = true
  warn_unused_configs = true
  warn_unreachable = true
  exclude = '''(^|/)tests/'''
  python_version = "3.10"
  plugins = ["numpy.typing.mypy_plugin",]

  [[tool.mypy.overrides]]
    module = "*/tests/*"
    ignore_errors = true

  [[tool.mypy.overrides]]
    module = "tests/*"
    ignore_errors = true


[tool.ruff]
line-length = 88
select = ["ALL"]
ignore = [
  "ANN101", "ANN102", "ANN401",
  "ARG001", "ARG002",
  "D105", "D107", "D203", "D213",
  "FBT003",
  "I001",
  "PD",
  "RET505", "RET506", "RET507",
]
